// apps/client-react/src/components/LostPasswordForm/LostPasswordForm.tsx
import { SendPasswordResetEmailDto } from '@daria/shared';
import { Form } from '../ui/form/Form';
import { FormControl } from '../ui/form/Control/Control';
import { TextInput } from '../ui/TextInput/TextInput';
import { Formik } from 'formik';
import { toFormikValidationSchema } from 'zod-formik-adapter';
import { ButtonCta } from '../ui/Button/Cta/Cta';
import { FormFooter } from '../ui/form/Footer/Footer';
import { FormError } from '../ui/form/Error/Error';
import styles from './LostPasswordForm.module.css';

export const LostPasswordForm = () => {
  const {
    mutate: sendPasswordEmail,
    error,
    reset,
    isSuccess
  } = useLostPassword();

  const initialValues = {
    email: ''
  };

  return (
    <Formik
      validationSchema={toFormikValidationSchema(SendPasswordResetEmailDto)}
      onSubmit={values => {
        reset();
        sendPasswordEmail(values);
      }}
      initialValues={initialValues}
    >
      {props => (
        <Form onSubmit={props.handleSubmit}>
          <FormControl id="lost-password-email" name="email" label="E-mail">
            {fieldProps => <TextInput {...fieldProps} />}
          </FormControl>

          <FormFooter>
            <ButtonCta type="submit">Send password reset email</ButtonCta>
          </FormFooter>

          {error && <FormError error={error.message} />}

          {isSuccess && (
            <p className={styles.successMessage}>
              If an account with this e-mail address exists on our platform, an
              e-mail will be sent shortly (usually immediately).
            </p>
          )}
        </Form>
      )}
    </Formik>
  );
};

// apps/client-vue/src/components/user/LostPasswordForm.vue
<script setup lang="ts">
import { SendPasswordResetEmailDto } from '@daria/shared';
import { toFormValidator } from '@vee-validate/zod';

const { mutate, error, isLoading, isSuccess } = useLostPassword();

const { handleSubmit } = useForm<SendPasswordResetEmailDto>({
  validationSchema: toFormValidator(SendPasswordResetEmailDto),
  initialValues: {
    email: ''
  }
});

const onSubmit = handleSubmit(values => {
  mutate(values);
});
</script>

<template>
  <UiForm @submit.prevent="onSubmit" class="signup-form">
    <UiFormControl
      id="signup-mail"
      v-slot="{ on, bind }"
      name="email"
      label="E-mail"
    >
      <UiTextInput v-bind="bind" type="email" v-on="on" />
    </UiFormControl>

    <UiFormFooter>
      <UiButtonCta :is-loading="isLoading">
        Send password reset email
      </UiButtonCta>
    </UiFormFooter>

    <UiFormError :error="error.message" v-if="error" />

    <p v-if="isSuccess">
      If an account with this e-mail address exists on our platform, an e-mail
      will be sent shortly (usually immediately).
    </p>
  </UiForm>
</template>

<style scoped>
p {
  font-weight: 700;
  margin-block: var(--space-5);
}
</style>
