// apps/client-react/src/components/VerifyemailReminder/VerifyEmailReminder.tsx
import { EmailVerificationModes } from '@daria/shared';
import { ButtonLink } from '../ui/Button/Link/Link';
import styles from './VerifyEmailReminder.module.css';

export const VerifyEmailReminder = () => {
  const { data: session } = useSession();
  const { data: featureFlags } = useFeatureFlags();
  const { mutate: resendEmail, isSuccess } = useSendVerificationEmail();

  const isDisplayed =
    session &&
    !session.verifiedAt &&
    featureFlags?.EMAIL_VERIFICATION_ON_SIGNUP ===
      EmailVerificationModes.REMINDER;

  if (!isDisplayed) return null;

  return (
    <div role="alert" className={styles.verifyEmailReminder}>
      You have not verified your account yet.
      <ButtonLink onClick={() => resendEmail(session!.email)}>
        Resend e-mail
      </ButtonLink>
      {isSuccess && (
        <span>
          Email sent successfully. If you can&apos;t find it, please check your
          spam folder.
        </span>
      )}
    </div>
  );
};

// apps/client-vue/src/components/user/VerifyEmailReminder.vue
<script setup lang="ts">
import { EmailVerificationModes } from '@daria/shared';

const { data: session } = useSession();
const { data: featureFlags } = useFeatureFlags();
const { mutate: resendEmail, isSuccess } = useSendVerificationEmail();

const isDisplayed = computed(
  () =>
    session.value &&
    !session.value.verifiedAt &&
    featureFlags.value?.EMAIL_VERIFICATION_ON_SIGNUP ===
      EmailVerificationModes.REMINDER
);
</script>

<template>
  <transition appear>
    <div role="alert" class="verify-email-reminder" v-if="isDisplayed">
      You have not verified your account yet.
      <UiButtonLink @click="resendEmail(session!.email)">
        Resend e-mail
      </UiButtonLink>

      <span v-if="isSuccess">
        Email sent successfully. If you can't find it, please check your spam
        folder.
      </span>
    </div>
  </transition>
</template>

<style scoped>
.verify-email-reminder {
  background-color: var(--color-warning);
  padding: var(--space-3);
  display: flex;
  align-items: center;
  gap: var(--space-5);
}

.v-enter-active,
.v-leave-active {
  transition: all var(--transition-md);
}
.v-enter-from,
.v-leave-to {
  transform: translateY(-1rem);
  opacity: 0;
}
</style>
