// apps/client-vue/src/components/user/SignupForm.vue
<script setup lang="ts">
import { useForm } from 'vee-validate';
import { toFormValidator } from '@vee-validate/zod';
import { SignUpDto } from '@daria/shared';
import { z } from 'zod';

const { push } = useRouter();
const {
  mutate: signup,
  isLoading,
  error
} = useSignup({
  onSuccess() {
    push({ name: 'Home' });
  }
});

const FormSchema = SignUpDto.extend({
  passwordConfirm: z.string(),
  isTosAccepted: z.boolean()
}).refine(data => data.password === data.passwordConfirm, {
  message: "Passwords don't match",
  path: ['passwordConfirm']
});
type FormSchema = z.infer<typeof FormSchema>;

const { data: featureFlags } = useFeatureFlags();
const { handleSubmit } = useForm<FormSchema>({
  validationSchema: toFormValidator(FormSchema),
  initialValues: {
    email: '',
    password: '',
    passwordConfirm: '',
    isTosAccepted: false
  }
});

const onSubmit = handleSubmit(values => {
  signup({
    ...values,
    tosAcceptedAt: values.isTosAccepted ? new Date() : undefined
  });
});
</script>

<template>
  <UiForm @submit.prevent="onSubmit" class="signup-form">
    <UiFormControl
      id="signup-mail"
      v-slot="{ on, bind }"
      name="email"
      label="E-mail"
    >
      <UiTextInput v-bind="bind" type="email" v-on="on" />
    </UiFormControl>

    <UiFormControl
      id="signup-password"
      v-slot="{ bind, on }"
      name="password"
      label="Password"
    >
      <UiPasswordInput v-bind="bind" v-on="on" />
    </UiFormControl>

    <UiFormControl
      id="signup-password-confirm"
      v-slot="{ bind, on }"
      name="passwordConfirm"
      label="Confirm your password"
    >
      <UiPasswordInput v-bind="bind" v-on="on" />
    </UiFormControl>

    <UiFormControl
      v-if="featureFlags?.ACCEPT_TOS_ON_SIGNUP"
      id="signup-tos-accepted-at"
      v-slot="{ bind, on }"
      name="isTosAccepted"
    >
      <UiCheckbox type="checkbox" v-bind="bind" v-on="on">
        I accept the terms and conditions
      </UiCheckbox>
    </UiFormControl>

    <UiFormFooter>
      <UiButtonCta :is-loading="isLoading">Sign up</UiButtonCta>
      <UiButtonLink to="/login">I don't have an account</UiButtonLink>
    </UiFormFooter>

    <UiFormError :error="error.message" v-if="error" />
  </UiForm>
</template>

<style scoped>
.signup-form {
  display: flex;
  flex-direction: column;
  gap: var(--space-4);
}
</style>

// apps/client-react/src/components/SignupForm/Signupform.tsx
import { SignUpDto } from '@daria/shared';
import { Form } from '../ui/form/Form';
import { FormControl } from '../ui/form/Control/Control';
import { TextInput } from '../ui/TextInput/TextInput';
import { Formik } from 'formik';
import { toFormikValidationSchema } from 'zod-formik-adapter';
import { ButtonCta } from '../ui/Button/Cta/Cta';
import { FormFooter } from '../ui/form/Footer/Footer';
import { ButtonLink } from '../ui/Button/Link/Link';
import { FormError } from '../ui/form/Error/Error';
import z from 'zod';
import { PasswordInput } from '../ui/PasswordInput/PasswordInput';
import { useFeatureFlags } from '@/hooks/useFeatureFlags';

const FormSchema = SignUpDto.extend({
  passwordConfirm: z.string(),
  isTosAccepted: z.boolean()
}).refine(data => data.password === data.passwordConfirm, {
  message: "Passwords don't match",
  path: ['passwordConfirm']
});
type FormSchema = z.infer<typeof FormSchema>;

export const SignupForm = () => {
  const { mutate: signup, error } = useSignup();

  const initialValues = {
    email: '',
    password: '',
    passwordConfirm: '',
    isTosAccepted: false
  };

  const { data: featureFlags } = useFeatureFlags();

  return (
    <Formik
      validationSchema={toFormikValidationSchema(FormSchema)}
      onSubmit={values => {
        signup({
          ...values,
          tosAcceptedAt: values.isTosAccepted ? new Date() : undefined
        });
      }}
      initialValues={initialValues}
    >
      {props => (
        <Form onSubmit={props.handleSubmit}>
          <FormControl id="signup-mail" name="email" label="E-mail">
            {fieldProps => <TextInput {...fieldProps} />}
          </FormControl>

          <FormControl id="signup-password" name="password" label="Password">
            {fieldProps => <PasswordInput {...fieldProps} />}
          </FormControl>

          <FormControl
            id="signup-password-confirm"
            name="passwordConfirm"
            label="Confirm your password"
          >
            {fieldProps => <PasswordInput {...fieldProps} />}
          </FormControl>

          {featureFlags?.ACCEPT_TOS_ON_SIGNUP && (
            <FormControl id="signup-tos-accepted" name="isTosAccepted">
              {fieldProps => (
                <label>
                  <input type="checkbox" {...fieldProps} />I accept the terms
                  and conditions.
                </label>
              )}
            </FormControl>
          )}

          <FormFooter>
            <ButtonCta type="submit">Sign up</ButtonCta>
            <ButtonLink to="/login">I don&apos;t have an account</ButtonLink>
          </FormFooter>

          {error && <FormError error={error.message} />}
        </Form>
      )}
    </Formik>
  );
};
