// packages/client-react/src/components/ui/TextInput/TextInput.tsx
import type { Nullable } from '@daria/shared';
import styles from './TextInput.module.css';
import { clsx } from 'clsx';
import type { ReactNode } from 'react';

type Props = {
  value: Nullable<string>;
  onChange: (val: string) => void;
  name: string;
  type?: string;
  id: string;
  disabled?: boolean;
  leftElement?: ReactNode;
  rightElement?: ReactNode;
};

export const TextInput = ({
  leftElement,
  rightElement,
  value,
  onChange,
  ...props
}: Props) => {
  return (
    <div
      className={clsx(styles.textInput, {
        left: !!leftElement,
        right: !!rightElement
      })}
    >
      {leftElement}

      <input
        {...props}
        value={value ?? ''}
        onChange={e => onChange(e.target.value)}
      />

      {rightElement}
    </div>
  );
};

// packages/client/src/components/ui/TextInput.vue
<script setup lang="ts">
import type { Nullable } from '@daria/shared';

const props = withDefaults(
  defineProps<{
    modelValue: Nullable<string>;
    name: string;
    type?: string;
    id: string;
    disabled?: boolean;
  }>(),
  { type: 'text', disabled: false }
);

const emit = defineEmits<{
  (e: 'update:modelValue', value: string): void;
}>();
const vModel = useVModel(props, 'modelValue', emit);
</script>

<template>
  <div style="display: flex">
    <slot name="left" />

    <input
      v-model="vModel"
      :id="props.id"
      :name="props.name"
      :type="props.type"
      :disabled="props.disabled"
    />
    <slot name="right" />
  </div>
</template>
