// apps/client-react/src/components/SignupForm/Signupform.tsx
import { SignUpDto } from '@daria/shared';
import { Form } from '../ui/form/Form';
import { FormControl } from '../ui/form/Control/Control';
import { TextInput } from '../ui/TextInput/TextInput';
import { Formik } from 'formik';
import { toFormikValidationSchema } from 'zod-formik-adapter';
import { ButtonCta } from '../ui/Button/Cta/Cta';
import { FormFooter } from '../ui/form/Footer/Footer';
import { ButtonLink } from '../ui/Button/Link/Link';
import { FormError } from '../ui/form/Error/Error';
import z from 'zod';
import { PasswordInput } from '../ui/PasswordInput/PasswordInput';

const FormSchema = SignUpDto.extend({
  passwordConfirm: z.string()
}).refine(data => data.password === data.passwordConfirm, {
  message: "Passwords don't match",
  path: ['passwordConfirm']
});
type FormSchema = z.infer<typeof FormSchema>;

export const SignupForm = () => {
  const { mutate: signup, error } = useSignup();

  const initialValues = {
    email: '',
    password: '',
    passwordConfirm: ''
  };

  return (
    <Formik
      validationSchema={toFormikValidationSchema(FormSchema)}
      onSubmit={values => {
        console.log(values);
        signup(values);
      }}
      initialValues={initialValues}
    >
      {props => (
        <Form onSubmit={props.handleSubmit}>
          <FormControl id="signup-mail" name="email" label="E-mail">
            {fieldProps => <TextInput {...fieldProps} />}
          </FormControl>

          <FormControl id="signup-password" name="password" label="Password">
            {fieldProps => <PasswordInput {...fieldProps} />}
          </FormControl>

          <FormControl
            id="signup-password-confirm"
            name="passwordConfirm"
            label="Confirm your password"
          >
            {fieldProps => <PasswordInput {...fieldProps} />}
          </FormControl>

          <FormFooter>
            <ButtonCta type="submit">Sign up</ButtonCta>
            <ButtonLink to="/login">I don&apos;t have an account</ButtonLink>
          </FormFooter>

          {error && <FormError error={error.message} />}
        </Form>
      )}
    </Formik>
  );
};

// packages/client/src/components/user/SignupForm.vue
<script setup lang="ts">
import { useForm } from 'vee-validate';
import { toFormValidator } from '@vee-validate/zod';
import { SignUpDto } from '@daria/shared';
import { z } from 'zod';

const { push } = useRouter();
const { mutate: login, reset } = useSignup({
  onSuccess() {
    push({ name: 'Home' });
  }
});

const FormSchema = SignUpDto.extend({
  passwordConfirm: z.string()
}).refine(data => data.password === data.passwordConfirm, {
  message: "Passwords don't match",
  path: ['passwordConfirm']
});
type FormSchema = z.infer<typeof FormSchema>;

const { handleSubmit } = useForm<FormSchema>({
  validationSchema: toFormValidator(FormSchema),
  initialValues: {
    email: '',
    password: '',
    passwordConfirm: ''
  }
});

const onSubmit = handleSubmit(values => {
  reset();
  login(values);
});
</script>

<template>
  <form space-y-5 @submit.prevent="onSubmit">
    <UiFormControl
      id="signup-mail"
      v-slot="{ on, bind }"
      name="email"
      label="E-mail"
    >
      <UiTextInput v-bind="bind" type="email" v-on="on" />
    </UiFormControl>

    <UiFormControl
      id="signup-password"
      v-slot="{ bind, on }"
      name="password"
      label="Password"
    >
      <UiPasswordInput v-bind="bind" v-on="on" />
    </UiFormControl>

    <UiFormControl
      id="signup-password-confirm"
      v-slot="{ bind, on }"
      name="passwordConfirm"
      label="Confirm your password"
    >
      <UiPasswordInput v-bind="bind" v-on="on" />
    </UiFormControl>

    <button>sign up</button>
  </form>
</template>

<style scoped></style>
