// apps/client-vue/src/components/app/ToSModal.vue
<script setup lang="ts">
import { useAcceptTos, useLatestTos } from '@/composables/tos';
import { isDefined } from '@daria/shared';

const props = defineProps<{ isOpened?: boolean }>();
const emit = defineEmits<{
  (e: 'update:isOpened', value: boolean): void;
}>();

const isControlled = computed(() => isDefined(props.isOpened));
const query = useLatestTos();
const { data: tos } = query;
const { data: session, refetch } = useSession();

const isOpened = computed({
  get() {
    if (isControlled.value) return props.isOpened as boolean;

    if (!session.value) return false;
    if (!tos.value) return false;
    if (!session.value.tosAcceptedAt) return true;

    return (
      tos.value.createdAt.getTime() > session.value.tosAcceptedAt?.getTime()
    );
  },
  set(val) {
    emit('update:isOpened', val);
  }
});

const { mutate: logout } = useLogout();
const { mutate: acceptTos } = useAcceptTos({
  onSuccess() {
    refetch();
  }
});
</script>

<template>
  <UiModal
    v-model:is-opened="isOpened"
    title="Terms and Conditions"
    :closable="isControlled"
  >
    <UiModalContent class="tos-modal">
      <p>Please accept our updated terms and conditions</p>
      <QueryLoader :query="query" v-slot="{ data }">
        <div class="content" v-html="data?.content" />
      </QueryLoader>

      <template #footer>
        <div class="footer-inner" v-if="!isControlled">
          <UiButtonCta variant="error" @click="logout(undefined)">
            Refuse
          </UiButtonCta>
          <UiButtonCta @click="acceptTos(undefined)">Accept</UiButtonCta>
        </div>
      </template>
    </UiModalContent>
  </UiModal>
</template>

<style>
.tos-modal {
  max-height: 75vh;
  overflow: auto;
}

.tos-modal .content {
  padding: var(--space-10);
}
.tos-modal .content ol {
  display: flex;
  flex-direction: column;
  line-height: 1.8;
  gap: var(--space-3);
  list-style-type: decimal;
}

.tos-modal .footer-inner {
  padding: var(--space-3);
  display: flex;
  justify-content: space-between;
}
</style>

// apps/client-react/src/components/TosModal/TosModal.tsx
import { isDefined, noop } from '@daria/shared';
import type { FC } from 'react';
import { Modal } from '../ui/Modal';
import { ModalContent } from '../ui/Modal/ModalContent/ModalContent';
import { ButtonCta } from '../ui/Button/Cta/Cta';
import styles from './TosModal.module.css';

type Props = { isOpened?: boolean; onChange?: (val: boolean) => void };

export const TosModal: FC<Props> = ({ isOpened, onChange }) => {
  const isControlled = useMemo(() => isDefined(isOpened), [isOpened]);

  const { data: tos } = useLatestTos();
  const { data: session, refetch } = useSession();

  const { mutate: logout } = useLogout();
  const { mutate: acceptTos } = useAcceptTos({
    onSuccess() {
      refetch();
    }
  });

  const _isOpened = useMemo(() => {
    if (isControlled) return isOpened as boolean;

    if (!session) return false;
    if (!tos) return false;
    if (!session.tosAcceptedAt) return true;
    return tos.createdAt.getTime() > session.tosAcceptedAt?.getTime();
  }, [isControlled, session, tos, isOpened]);

  return (
    <Modal
      isOpened={_isOpened}
      onChange={onChange ?? noop}
      title="Terms and Conditions"
      closable={isControlled}
    >
      <ModalContent
        className={styles.tosModal}
        footerElement={
          !isControlled && (
            <div className={styles.footerInner}>
              <ButtonCta variant="error" onClick={() => logout(undefined)}>
                Refuse
              </ButtonCta>
              <ButtonCta onClick={() => acceptTos(undefined)}>Accept</ButtonCta>
            </div>
          )
        }
      >
        <p>Please accept our updated terms and conditions</p>

        {tos && (
          <div
            className={styles.content}
            dangerouslySetInnerHTML={{ __html: tos.content }}
          />
        )}
      </ModalContent>
    </Modal>
  );
};
