// apps/client-vue/src/components/auth/LoginForm.vue
<script setup lang="ts">
import { useForm } from 'vee-validate';
import { toFormValidator } from '@vee-validate/zod';
import { ErrorKinds, LoginDto } from '@daria/shared';

const { mutate: login, isLoading, error } = useLogin();

const { handleSubmit, values } = useForm<LoginDto>({
  validationSchema: toFormValidator(LoginDto)
});

const onSubmit = handleSubmit(values => {
  login(values);
});

const { mutate: sendVerificationEmail } = useSendVerificationEmail();
const isVerificationLinkDisplayed = computed(
  () => error.value?.data?.kind === ErrorKinds.EMAIL_NOT_VERIFIED
);
</script>

<template>
  <UiForm @submit.prevent="onSubmit" class="login-form">
    <UiFormControl
      id="login-mail"
      v-slot="{ on, bind }"
      name="email"
      label="E-mail"
    >
      <UiTextInput v-bind="bind" type="email" v-on="on" />
    </UiFormControl>

    <UiFormControl
      id="login-password"
      v-slot="{ bind, on }"
      name="password"
      label="Password"
    >
      <UiPasswordInput v-bind="bind" v-on="on" />
    </UiFormControl>

    <UiFormFooter>
      <UiButtonCta :is-loading="isLoading">Login</UiButtonCta>
      <UiButtonLink to="/lost-password">Forgot your password ?</UiButtonLink>
    </UiFormFooter>

    <div class="error">
      <UiFormError :error="error.message" v-if="error" />
      <UiButtonLink
        type="button"
        v-if="isVerificationLinkDisplayed"
        @click="sendVerificationEmail(values.email)"
      >
        Resend confirmation email
      </UiButtonLink>
    </div>
  </UiForm>
</template>

<style scoped lang="postcss">
.login-form {
  display: flex;
  flex-direction: column;
  gap: var(--space-4);
}

.error {
  display: flex;
  align-items: center;
  gap: var(--space-4);
}
</style>

// apps/client-react/src/components/LoginForm/LoginForm.tsx
import { ErrorKinds, LoginDto } from '@daria/shared';
import { Form } from '../ui/form/Form';
import { FormControl } from '../ui/form/Control/Control';
import { TextInput } from '../ui/TextInput/TextInput';
import { Formik } from 'formik';
import { toFormikValidationSchema } from 'zod-formik-adapter';
import { ButtonCta } from '../ui/Button/Cta/Cta';
import { FormFooter } from '../ui/form/Footer/Footer';
import { ButtonLink } from '../ui/Button/Link/Link';
import { FormError } from '../ui/form/Error/Error';
import { PasswordInput } from '../ui/PasswordInput/PasswordInput';
import styles from './LoginForm.module.css';

export const LoginForm = () => {
  const { mutate: login, error } = useLogin();
  const { mutate: sendVerificationEmail } = useSendVerificationEmail();

  const isVerificationLinkDisplayed =
    error?.data?.kind === ErrorKinds.EMAIL_NOT_VERIFIED;

  const initialValues = {
    email: '',
    password: ''
  };
  const onSubmit = (values: LoginDto) => login(values);
  return (
    <Formik
      validationSchema={toFormikValidationSchema(LoginDto)}
      onSubmit={onSubmit}
      initialValues={initialValues}
    >
      {props => (
        <Form onSubmit={props.handleSubmit}>
          <FormControl id="signup-mail" name="email" label="E-mail">
            {fieldProps => <TextInput {...fieldProps} />}
          </FormControl>

          <FormControl id="signup-password" name="password" label="Password">
            {fieldProps => <PasswordInput {...fieldProps} />}
          </FormControl>

          <FormFooter>
            <ButtonCta type="submit">Login</ButtonCta>
            <ButtonLink to="/lost-password">Forgot your password ?</ButtonLink>
          </FormFooter>

          {error && (
            <div className={styles.error}>
              <FormError error={error.message} />
              {isVerificationLinkDisplayed && (
                <ButtonLink
                  type="button"
                  onClick={() => sendVerificationEmail(props.values.email)}
                >
                  Resend confirmation email
                </ButtonLink>
              )}
            </div>
          )}
        </Form>
      )}
    </Formik>
  );
};
