// apps/client-vue/src/components/ui/button/Full.vue
<script setup lang="ts">
const props = withDefaults(defineProps<{ variant?: 'primary' | 'error' }>(), {
  variant: 'primary'
});

const colors = computed(() => ({
  bg: `var(--color-${props.variant})`,
  bgHover: `var(--color-${props.variant}-dark)`,
  bgFocus: `var(--color-${props.variant}-darker)`,
  text: `var(--color-on-${props.variant})`,
  textHover: `var(--color-on-${props.variant}-dark)`,
  textFocus: `var(--color-on-${props.variant}-darker)`
}));
</script>

<template>
  <UiButtonBase class="button-full">
    <template #left><slot name="left" /></template>
    <slot />
    <template #right><slot name="left" /></template>
  </UiButtonBase>
</template>

<style scoped>
.button-full {
  background-color: v-bind('colors.bg');
  color: v-bind('colors.text');
}
.button-full:hover {
  background-color: v-bind('colors.bgHover');
  color: v-bind('colors.textHover');
}
.button-full:focus-visible {
  background-color: v-bind('colors.bgFocus');
  color: v-bind('colors.textFocus');
}
</style>

// apps/client-react/src/components/ui/Button/Full/Full.tsx
import type {
  CSSProperties,
  FC,
  HTMLAttributes,
  PropsWithChildren,
  ReactNode
} from 'react';
import { ButtonBase } from '@/components/ui/Button/Base/Base';
import styles from './Full.module.css';
import clsx from 'clsx';

export type ButtonFullVariant = 'primary' | 'error';

type Props = HTMLAttributes<HTMLButtonElement> & {
  isLoading?: boolean;
  size?: 'sm' | 'md' | 'lg' | 'xl';
  to?: string;
  disabled?: boolean;
  leftElement?: ReactNode;
  rightElement?: ReactNode;
  type?: 'submit' | 'button' | 'reset';
  variant?: ButtonFullVariant;
};

export const ButtonFull: FC<PropsWithChildren<Props>> = ({
  className,
  children,
  variant = 'primary',
  ...props
}) => {
  const style = {
    '--button-full-bg': `var(--color-${variant})`,
    ['--button-full-bgHover']: `var(--color-${variant}-dark)`,
    ['--button-full-bgFocus']: `var(--color-${variant}-darker)`,
    ['--button-full-text']: `var(--color-on-${variant})`,
    ['--button-full-textHover']: `var(--color-on-${variant}-dark)`,
    ['--button-full-textFocus']: `var(--color-on-${variant}-darker)`
  } as CSSProperties;

  return (
    <ButtonBase
      className={clsx(styles.buttonFull, className)}
      style={style}
      {...props}
    >
      {children}
    </ButtonBase>
  );
};
