// apps/client-react/src/pages/lost-password.tsx
import { LostPasswordForm } from '@/components/LostPasswordForm/LostPasswordForm';
import { PageTitle } from '@/components/PageTitle/PageTitle';
import { PublicOnlyRoute } from '@/components/PublicOnlyRoute';
import { Container } from '@/components/ui/Container/Container';
import { Surface } from '@/components/ui/Surface/Surface';

export default function LostPasswordPage() {
  return (
    <PublicOnlyRoute>
      <Container className="page" size="sm">
        <Surface as="section">
          <PageTitle>Lost your password?</PageTitle>
          <p>
            Please fill the form below. We will send you an e-mail containing a
            link to select a new password.
          </p>
          <LostPasswordForm />
        </Surface>
      </Container>
    </PublicOnlyRoute>
  );
}

// apps/client-vue/src/pages/lost-password.vue
<template>
  <UiContainer size="sm" class="lost-password-page">
    <UiSurface as="section">
      <AppPageTitle>Lost your password ?</AppPageTitle>
      <p>
        Please fill the form below. We will send you an e-mail containing a link
        to select a new password.
      </p>
      <UserLostPasswordForm />
    </UiSurface>
  </UiContainer>
</template>

<style scoped>
.lost-password-page {
  margin-block-start: var(--space-15);
}

p {
  margin-block: var(--space-5);
}
</style>

<route lang="json">
{ "name": "LostPassword", "meta": { "publicOnly": true } }
</route>
