// apps/client-vue/src/pages/reset-password.vue
<script setup lang="ts">
import { isString } from '@daria/shared';

const route = useRoute();
</script>
<template>
  <UiContainer size="sm" class="reset-password-page">
    <UiSurface as="section">
      <AppPageTitle>Reset your password</AppPageTitle>
      <router-link v-if="!isString(route.query.token)" to="/lost-password">
        Click here to request a password reset email
      </router-link>

      <UserResetPasswordForm v-else :token="route.query.token" />
    </UiSurface>
  </UiContainer>
</template>

<style scoped>
.reset-password-page {
  margin-block-start: var(--space-15);
}
</style>

<route lang="json">
{ "name": "ResetPassword", "meta": { "publicOnly": true } }
</route>

// apps/client-react/src/pages/reset-password.tsx
import { PageTitle } from '@/components/PageTitle/PageTitle';
import { PublicOnlyRoute } from '@/components/PublicOnlyRoute';
import { ResetPasswordForm } from '@/components/ResetPasswordForm/ResetPasswormForm';
import { ButtonLink } from '@/components/ui/Button/Link/Link';
import { Container } from '@/components/ui/Container/Container';
import { Surface } from '@/components/ui/Surface/Surface';
import { useSearchParams } from 'react-router-dom';

export default function LostPasswordPage() {
  const [searchParams] = useSearchParams();
  const token = searchParams.get('token');

  return (
    <PublicOnlyRoute>
      <Container className="page" size="sm">
        <Surface as="section">
          <PageTitle>Reset your password</PageTitle>
          {token ? (
            <ResetPasswordForm token={token} />
          ) : (
            <ButtonLink to="/lost-password">
              Click here to request a password reset email
            </ButtonLink>
          )}
        </Surface>
      </Container>
    </PublicOnlyRoute>
  );
}
