// apps/client-vue/src/components/ui/PasswordInput.vue
<script setup lang="ts">
import type { Nullable } from '@daria/shared';
import EyeIcon from '~icons/mdi/eye';
import EyeOffIcon from '~icons/mdi/eye-off';

const props = defineProps<{
  name: string;
  id: string;
  modelValue: Nullable<string>;
}>();
const emit = defineEmits<{
  (e: 'update:modelValue', value: string): void;
}>();

const vModel = useVModel(props, 'modelValue', emit);
const isPasswordShown = ref(false);
const type = computed(() => (isPasswordShown.value ? 'text' : 'password'));

const icon = computed(() => (isPasswordShown.value ? EyeOffIcon : EyeIcon));
</script>

<template>
  <UiTextInput v-model="vModel" :id="props.id" :name="props.name" :type="type">
    <template #right>
      <UiButtonIcon
        type="button"
        :title="isPasswordShown ? 'hide password' : 'show password'"
        @click="isPasswordShown = !isPasswordShown"
      >
        <component :is="icon" />
      </UiButtonIcon>
    </template>
  </UiTextInput>
</template>

// apps/client-react/src/components/ui/PasswordInput/PasswordInput.tsx
import type { HTMLAttributes, ReactNode } from 'react';
import { ButtonIcon } from '../Button/Icon/Icon';
import { TextInput } from '../TextInput/TextInput';
import EyeIcon from '~icons/mdi/eye';
import EyeOffIcon from '~icons/mdi/eye-off';
import type { Nullable } from '@daria/shared';

type Props = HTMLAttributes<HTMLInputElement> & {
  value: Nullable<string>;
  id: string;
  leftElement?: ReactNode;
  type: never;
};

export const PasswordInput = (props: Props) => {
  const [isPasswordShown, setIsPasswordShown] = useState(false);

  const type = isPasswordShown ? 'text' : 'password';
  const toggle = () => setIsPasswordShown(shown => !shown);

  const IconComponent = useMemo(
    () => (isPasswordShown ? EyeOffIcon : EyeIcon),
    [isPasswordShown]
  );

  return (
    <TextInput
      {...props}
      type={type}
      rightElement={
        <ButtonIcon
          type="button"
          title={isPasswordShown ? 'hide password' : 'show password'}
          onClick={toggle}
        >
          <IconComponent />
        </ButtonIcon>
      }
    />
  );
};
