// packages/client/src/components/auth/LoginForm.vue
<script setup lang="ts">
import { useForm } from 'vee-validate';
import { toFormValidator } from '@vee-validate/zod';
import { LoginDto } from '@daria/shared';

const { mutate: login, reset } = useLogin();

const { handleSubmit } = useForm<LoginDto>({
  validationSchema: toFormValidator(LoginDto),
  initialValues: {
    email: '',
    password: ''
  }
});

const onSubmit = handleSubmit(values => {
  reset();
  login(values);
});
</script>

<template>
  <form space-y-5 @submit.prevent="onSubmit">
    <UiFormControl
      id="signup-mail"
      v-slot="{ on, bind }"
      name="email"
      label="E-mail"
    >
      <UiTextInput v-bind="bind" type="email" v-on="on" />
    </UiFormControl>

    <UiFormControl
      id="signup-password"
      v-slot="{ bind, on }"
      name="password"
      label="Password"
    >
      <UiTextInput v-bind="bind" v-on="on" />
    </UiFormControl>

    <button>Login</button>
  </form>
</template>

<style scoped></style>

// packages/client-react/src/components/LoginForm/LoginForm.tsx
import { LoginDto } from '@daria/shared';
import { zodResolver } from '@hookform/resolvers/zod';
import { Form } from '../ui/form/Form';
import { FormControl } from '../ui/form/Control/Control';
import { TextInput } from '../ui/TextInput/TextInput';
import { Formik } from 'formik';
import { toFormikValidationSchema } from 'zod-formik-adapter';
import { ButtonBase } from '../ui/Button/Base/Base';

export const LoginForm = () => {
  const { mutate: login, isLoading, error, reset } = useLogin();

  const initialValues = {
    email: '',
    password: ''
  };

  return (
    <Formik
      validationSchema={toFormikValidationSchema(LoginDto)}
      onSubmit={values => {
        reset();
        login(values);
      }}
      initialValues={initialValues}
    >
      {props => (
        <Form onSubmit={props.handleSubmit}>
          <FormControl id="signup-mail" name="email" label="E-mail">
            {fieldProps => <TextInput {...fieldProps} />}
          </FormControl>

          <FormControl id="signup-password" name="password" label="Password">
            {fieldProps => <TextInput {...fieldProps} />}
          </FormControl>

          <ButtonBase>Login</ButtonBase>
        </Form>
      )}
    </Formik>
  );
};
